research_task:
  description: >
    1. Research and identify 3-5 classic feature extraction methods in {topic} typically used in the domain that can be implemented directly in Scikit-learn transformers.
    2. Research 3-5 innovative ideas for feature extraction from similar domains or novel approaches that can also be implemented in Scikit-learn transformers.
    3. Provide brief explanations of why these methods may be applicable to the given problem and ensure they are implementable.
  expected_output: >
    A list of 3-5 classic feature extraction methods and 3-5 innovative methods, each ready to be implemented as a Scikit-learn transformer.
  agent: researcher

coding_task:
  description: >
    1. Implement all the feature extraction techniques from the following list: {topic}.
    2. Ensure the code is clean, well-commented, and ready for production use.
    3. Focus only on implementing the custom feature extraction transformers, without integrating them into a Scikit-learn pipeline.
  expected_output: >
    A Python file with the custom feature extraction transformers, without integration into a pipeline.
  agent: coder

review_task:
  description: >
    1. Review the code generated by the Coder for clarity and correctness.
    2. Provide an executive summary explaining the feature extraction techniques implemented from the following list: {topic}.
    3. Include the code for each feature extraction method in the summary, as well as a rationale for why these methods are useful for the given topic.
  expected_output: >
    A final Python file with comments and an executive summary explaining the feature extraction approach, distinguishing between classical and innovative techniques.
  agent: reviewer
